### ISSUE TITLE
[BUG] Can't play music on my phone

### ISSUE THREAD

**Issue by Tyger375** [CollotsSpot/Ensemble#17]
I'm assuming this is a bug since there's written that the app should be able to stream music directly onto my device.
however, the app doesn't give me the option, as it only shows me available google Chromecast devices
![Screenshot_20251218_192822.jpg](https://github.com/user-attachments/assets/baf1e3e6-823e-4024-a155-00e05eceb46a)

**Comment by Tyger375** [comment]
sorry I've just read the part that says latest beta doesn't support that anymore 😅

**Comment by CollotsSpot** [comment]
Actually it should now since version 2.0.0. can you give me some logs? And some info about your setup. 

I guess you have music assistant Auth? The local device name is your display name or username if display name not set in music assistant. So in my case it's Chris' Phone.

**Comment by Tyger375** [comment]
these are the logs:
[07:31:12.642] INFO  🎵 AudioService initialized - background playback and media notifications ENABLED
[07:31:12.682] INFO  🚀 AppStartup: Waiting for provider auto-connection to http://192.168.1.100
[07:31:12.685] INFO  🔐 Restoring saved auth credentials...
[07:31:12.685] INFO  ✓ Restored music_assistant credentials from storage
[07:31:12.685] INFO  🔐 Auth credentials restored: music_assistant
[07:31:12.690] INFO  Original server URL: http://192.168.1.100
[07:31:12.690] INFO  Using WebSocket session ID: session_32716b1b-34aa-4684-a981-8754752b33eb
[07:31:12.690] INFO  Using port 8095 for unsecure connection
[07:31:12.690] INFO  Attempting unsecure (WS) connection
[07:31:12.690] INFO  Final WebSocket URL: ws://192.168.1.100:8095/ws?client_id=session_32716b1b-34aa-4684-a981-8754752b33eb
[07:31:12.690] INFO  Connection: No authentication configured
[07:31:12.905] INFO  Received message: (server_id, server_version, schema_version, ..., homeassistant_addon, onboard_done)
[07:31:12.905] INFO  Received server info: 2.7.0 (schema: 28)
[07:31:12.905] INFO  Server: Requires authentication
[07:31:12.905] INFO  🔗 WebSocket connected to MA server
[07:31:12.905] INFO  🔐 MA auth required, attempting authentication...
[07:31:12.905] INFO  Connection: Connected to server
[07:31:12.905] INFO  🔐 Trying stored MA token...
[07:31:12.905] INFO  🔐 Authenticating WebSocket with token...
[07:31:12.918] INFO  Received message: (message_id, result, partial)
[07:31:12.918] INFO  ✅ WebSocket authenticated successfully
[07:31:12.918] INFO  ✅ MA authentication with stored token successful
[07:31:12.918] INFO  ✅ MA authentication successful
[07:31:12.918] INFO  🚀 Initializing after connection...
[07:31:12.919] INFO  📥 Fetching initial state...
[07:31:12.932] INFO  🚀 AppStartup: Connection established
[07:31:12.947] INFO  🔄 Fetching fresh recent albums...
[07:31:12.948] INFO  🔄 Fetching fresh discover artists...
[07:31:12.949] INFO  🔄 Fetching fresh discover albums...
[07:31:12.959] INFO  Received message: (message_id, result, partial)
[07:31:12.959] INFO  🔍 auth/me raw response keys: [message_id, result, partial]
[07:31:12.959] INFO  ✓ Got user info: username=edoar, display_name=null
[07:31:12.960] INFO  ✅ Set owner name from MA profile: edoar
[07:31:13.510] INFO  Received message: (message_id, result, partial)
[07:31:13.511] INFO  Received message: (message_id, result, partial)
[07:31:13.511] INFO  ✓ Provider manifests loaded
[07:31:13.512] INFO  Received message: (message_id, result, partial)
[07:31:13.512] INFO  Received message: (message_id, result, partial)
[07:31:13.513] INFO  Received message: (message_id, result, partial)
[07:31:13.514] INFO  ✅ Cached 10 discover albums
[07:31:13.514] INFO  ✅ Cached 10 discover artists
[07:31:13.530] DEBUG [ArtistCard] No MA image for "Lil Wayne", trying fallback
[07:31:13.530] DEBUG [ArtistCard] No MA image for "Slait", trying fallback
[07:31:13.530] DEBUG [ArtistCard] No MA image for "DJ Esco", trying fallback
[07:31:13.530] DEBUG [ArtistCard] No MA image for "No Savage", trying fallback
[07:31:13.530] DEBUG [ArtistCard] No MA image for "Nas", trying fallback
[07:31:13.532] INFO  Received message: (message_id, result, partial)
[07:31:13.532] INFO  Received message: (message_id, result, partial)
[07:31:13.532] INFO  ✓ Provider instances loaded
[07:31:13.532] INFO  ✅ Initial state fetch complete
[07:31:13.533] INFO  📚 Fetched 1 recent albums using 1 batch requests
[07:31:13.533] INFO  ✅ Cached 1 recent albums
[07:31:13.541] INFO  Received message: (message_id, result, partial)
[07:31:13.541] INFO  🔍 auth/me raw response keys: [message_id, result, partial]
[07:31:13.541] INFO  ✓ Got user info: username=edoar, display_name=null
[07:31:13.543] INFO  ✅ Set owner name from MA profile: edoar
[07:31:13.543] INFO  Using existing player ID: ensemble_178dd23e-752e-42b5-b61e-31b2d73ecd2b
[07:31:13.543] INFO  🆔 Using player ID: ensemble_178dd23e-752e-42b5-b61e-31b2d73ecd2b
[07:31:13.557] INFO  Received message: (message_id, result, partial)
[07:31:13.558] INFO  🆔 Player not found in MA, registering as new
[07:31:13.558] INFO  🎵 Registering player with MA: id=ensemble_178dd23e-752e-42b5-b61e-31b2d73ecd2b, name=edoar's Phone
[07:31:13.558] INFO  Player: Registering "edoar's Phone" (attempt 1/3)
[07:31:13.564] INFO  Received message: (message_id, error_code, details)
[07:31:13.564] INFO  Command error: 12 - Invalid command: builtin_player/register
[07:31:13.564] INFO  Player: Registration attempt 1 failed - Exception: 12: Invalid command: builtin_player/register
[07:31:13.564] INFO  Player: Retrying... (attempt 2/3)
[07:31:13.832] DEBUG [ArtistCard] Found fallback image for "Nas"
[07:31:13.834] DEBUG [ArtistCard] Found fallback image for "Lil Wayne"
[07:31:13.837] DEBUG [ArtistCard] Found fallback image for "Slait"
[07:31:13.847] DEBUG [ArtistCard] Found fallback image for "No Savage"
[07:31:13.893] DEBUG [ArtistCard] Found fallback image for "DJ Esco"
[07:31:14.065] INFO  Player: Registering "edoar's Phone" (attempt 2/3)
[07:31:14.076] INFO  Received message: (message_id, error_code, details)
[07:31:14.076] INFO  Command error: 12 - Invalid command: builtin_player/register
[07:31:14.076] INFO  Player: Registration attempt 2 failed - Exception: 12: Invalid command: builtin_player/register
[07:31:14.076] INFO  Player: Retrying... (attempt 3/3)
[07:31:15.077] INFO  Player: Registering "edoar's Phone" (attempt 3/3)
[07:31:15.107] INFO  Received message: (message_id, error_code, details)
[07:31:15.108] INFO  Command error: 12 - Invalid command: builtin_player/register
[07:31:15.108] INFO  Player: Registration attempt 3 failed - Exception: 12: Invalid command: builtin_player/register
[07:31:15.108] INFO  Player: All 3 registration attempts failed
[07:31:15.108] INFO  ⚠️ Builtin player API not available (MA 2.7.0b20+ uses Sendspin)
[07:31:15.108] INFO  🔄 Attempting Sendspin connection...
[07:31:15.108] INFO  PcmAudioPlayer: Initializing (48000Hz, 2ch, 16bit)
[07:31:15.140] INFO  PcmAudioPlayer: Initialized successfully
[07:31:15.141] INFO  ✅ PCM audio player initialized for Sendspin
[07:31:15.141] INFO  PcmAudioPlayer: Connecting to audio stream
[07:31:15.141] INFO  Using existing player ID: ensemble_178dd23e-752e-42b5-b61e-31b2d73ecd2b
[07:31:15.141] INFO  Sendspin: Getting connection info for player ensemble_178dd23e-752e-42b5-b61e-31b2d73ecd2b
[07:31:15.149] INFO  Received message: (message_id, result, partial)
[07:31:15.149] INFO  Sendspin: Got connection info - local_ws_url: ws://192.168.1.100:8927/sendspin
[07:31:15.149] INFO  Sendspin: ICE servers count: 3
[07:31:15.149] INFO  Sendspin: Trying local WebSocket URL: ws://192.168.1.100:8927/sendspin
[07:31:15.149] INFO  Using existing player ID: ensemble_178dd23e-752e-42b5-b61e-31b2d73ecd2b
[07:31:15.149] INFO  Sendspin: Connecting with URL: ws://192.168.1.100:8927/sendspin
[07:31:15.149] INFO  Sendspin: Connecting to ws://192.168.1.100:8927/sendspin
[07:31:20.151] INFO  Sendspin: Connection attempt failed: TimeoutException after 0:00:05.000000: Future not completed
[07:31:20.151] INFO  ⚠️ Sendspin: WebRTC fallback not yet implemented
[07:31:20.151] INFO  ℹ️ For external access, configure /sendspin route in your reverse proxy
[07:31:20.151] INFO  ⚠️ Sendspin connection failed - local player unavailable
[07:31:20.151] INFO  ℹ️ Use other players (Chromecast, etc) or ensure /sendspin route is configured
[07:31:20.161] INFO  Received message: (message_id, result, partial)
[07:31:20.161] INFO  🎛️ getPlayers returned 10 players:
[07:31:20.161] INFO  🎛️ After filtering: 10 players available
[07:31:20.161] INFO  🔄 Auto-selected last used player: Papà google
[07:31:20.161] INFO  🖼️ Preloading track info for all 10 players...
[07:31:20.161] INFO  🔍 Preload Camera dei BOSS: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Camera dei BOSS: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Camera Edo speaker: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Camera Edo speaker: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Camera Eva speaker: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Camera Eva speaker: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Casa: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Casa: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Ingresso TV: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Ingresso TV: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Papà google: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Papà google: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Studio: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Studio: SKIPPED - not available or powered
[07:31:20.161] INFO  🔍 Preload Zone Giorno: state=idle, available=true
[07:31:20.161] INFO  🔍 Preload Zone Giorno: SKIPPED - not available or powered
[07:31:20.162] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:20.162] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:20.162] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:20.162] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:20.162] INFO  🖼️ Preloading complete
[07:31:20.163] INFO  ✅ Post-connection initialization complete
[07:31:20.177] INFO  Received message: (message_id, result, partial)
[07:31:20.189] INFO  Received message: (message_id, result, partial)
[07:31:20.267] INFO  Received message: (message_id, result, partial)
[07:31:20.419] INFO  Received message: (message_id, result, partial)
[07:31:21.745] INFO  📱 App resumed - checking WebSocket connection...
[07:31:21.745] INFO  🔄 checkAndReconnect called - state: MAConnectionState.authenticated
[07:31:21.745] INFO  🔄 Already connected, verifying connection...
[07:31:21.760] INFO  Received message: (message_id, result, partial)
[07:31:21.760] INFO  🎛️ getPlayers returned 10 players:
[07:31:21.760] INFO  🎛️ After filtering: 10 players available
[07:31:21.760] INFO  🖼️ Preloading track info for all 10 players...
[07:31:21.760] INFO  🔍 Preload Camera dei BOSS: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Camera dei BOSS: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Camera Edo speaker: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Camera Edo speaker: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Camera Eva speaker: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Camera Eva speaker: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Casa: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Casa: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Ingresso TV: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Ingresso TV: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Papà google: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Papà google: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Studio: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Studio: SKIPPED - not available or powered
[07:31:21.760] INFO  🔍 Preload Zone Giorno: state=idle, available=true
[07:31:21.760] INFO  🔍 Preload Zone Giorno: SKIPPED - not available or powered
[07:31:21.761] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:21.761] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:21.761] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:21.761] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:21.761] INFO  🖼️ Preloading complete
[07:31:21.809] INFO  Received message: (message_id, result, partial)
[07:31:21.809] INFO  Received message: (message_id, result, partial)
[07:31:21.809] INFO  🔄 Connection verified, players and state refreshed
[07:31:23.498] INFO  🔍 Preload Camera dei BOSS: state=idle, available=true
[07:31:23.498] INFO  🔍 Preload Camera dei BOSS: SKIPPED - not available or powered
[07:31:23.498] INFO  🔍 Preload Camera Edo speaker: state=idle, available=true
[07:31:23.498] INFO  🔍 Preload Camera Edo speaker: SKIPPED - not available or powered
[07:31:23.498] INFO  🔍 Preload Camera Eva speaker: state=idle, available=true
[07:31:23.498] INFO  🔍 Preload Camera Eva speaker: SKIPPED - not available or powered
[07:31:23.498] INFO  🔍 Preload Casa: state=idle, available=true
[07:31:23.498] INFO  🔍 Preload Casa: SKIPPED - not available or powered
[07:31:23.498] INFO  🔍 Preload Ingresso TV: state=idle, available=true
[07:31:23.498] INFO  🔍 Preload Ingresso TV: SKIPPED - not available or powered
[07:31:23.498] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:23.498] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:23.498] INFO  🔍 Preload Papà google: state=idle, available=true
[07:31:23.498] INFO  🔍 Preload Papà google: SKIPPED - not available or powered
[07:31:23.499] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:23.499] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:23.499] INFO  🔍 Preload Studio: state=idle, available=true
[07:31:23.499] INFO  🔍 Preload Studio: SKIPPED - not available or powered
[07:31:23.499] INFO  🔍 Preload Zone Giorno: state=idle, available=true
[07:31:23.499] INFO  🔍 Preload Zone Giorno: SKIPPED - not available or powered
[07:31:26.775] INFO  Received message: (message_id, result, partial)
[07:31:28.503] INFO  🔍 Preload Camera dei BOSS: state=idle, available=true
[07:31:28.503] INFO  🔍 Preload Camera dei BOSS: SKIPPED - not available or powered
[07:31:28.503] INFO  🔍 Preload Camera Edo speaker: state=idle, available=true
[07:31:28.503] INFO  🔍 Preload Camera Edo speaker: SKIPPED - not available or powered
[07:31:28.503] INFO  🔍 Preload Camera Eva speaker: state=idle, available=true
[07:31:28.503] INFO  🔍 Preload Camera Eva speaker: SKIPPED - not available or powered
[07:31:28.503] INFO  🔍 Preload Casa: state=idle, available=true
[07:31:28.503] INFO  🔍 Preload Casa: SKIPPED - not available or powered
[07:31:28.503] INFO  🔍 Preload Ingresso TV: state=idle, available=true
[07:31:28.503] INFO  🔍 Preload Ingresso TV: SKIPPED - not available or powered
[07:31:28.504] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:28.504] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:28.504] INFO  🔍 Preload Papà google: state=idle, available=true
[07:31:28.504] INFO  🔍 Preload Papà google: SKIPPED - not available or powered
[07:31:28.504] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:28.504] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:28.504] INFO  🔍 Preload Studio: state=idle, available=true
[07:31:28.504] INFO  🔍 Preload Studio: SKIPPED - not available or powered
[07:31:28.504] INFO  🔍 Preload Zone Giorno: state=idle, available=true
[07:31:28.504] INFO  🔍 Preload Zone Giorno: SKIPPED - not available or powered
[07:31:28.509] INFO  Received message: (message_id, result, partial)
[07:31:28.509] INFO  🎛️ getPlayers returned 10 players:
[07:31:28.509] INFO  🎛️ After filtering: 10 players available
[07:31:28.509] INFO  🖼️ Preloading track info for all 10 players...
[07:31:28.510] INFO  🔍 Preload Camera dei BOSS: state=idle, available=true
[07:31:28.510] INFO  🔍 Preload Camera dei BOSS: SKIPPED - not available or powered
[07:31:28.510] INFO  🔍 Preload Camera Edo speaker: state=idle, available=true
[07:31:28.510] INFO  🔍 Preload Camera Edo speaker: SKIPPED - not available or powered
[07:31:28.510] INFO  🔍 Preload Camera Eva speaker: state=idle, available=true
[07:31:28.510] INFO  🔍 Preload Camera Eva speaker: SKIPPED - not available or powered
[07:31:28.510] INFO  🔍 Preload Casa: state=idle, available=true
[07:31:28.510] INFO  🔍 Preload Casa: SKIPPED - not available or powered
[07:31:28.510] INFO  🔍 Preload Ingresso TV: state=idle, available=true
[07:31:28.510] INFO  🔍 Preload Ingresso TV: SKIPPED - not available or powered
[07:31:28.510] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:28.510] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:28.511] INFO  🔍 Preload Papà google: state=idle, available=true
[07:31:28.511] INFO  🔍 Preload Papà google: SKIPPED - not available or powered
[07:31:28.511] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:28.511] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:28.511] INFO  🔍 Preload Studio: state=idle, available=true
[07:31:28.511] INFO  🔍 Preload Studio: SKIPPED - not available or powered
[07:31:28.511] INFO  🔍 Preload Zone Giorno: state=idle, available=true
[07:31:28.511] INFO  🔍 Preload Zone Giorno: SKIPPED - not available or powered
[07:31:28.513] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:28.513] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:28.513] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:28.513] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:28.513] INFO  🖼️ Preloading complete
[07:31:28.518] INFO  Received message: (message_id, result, partial)
[07:31:33.500] INFO  🔍 Preload Camera dei BOSS: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Camera dei BOSS: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Camera Edo speaker: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Camera Edo speaker: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Camera Eva speaker: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Camera Eva speaker: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Casa: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Casa: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Ingresso TV: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Ingresso TV: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload KD-65X8509C: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload KD-65X8509C: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Papà google: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Papà google: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Sala e studio: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Sala e studio: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Studio: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Studio: SKIPPED - not available or powered
[07:31:33.501] INFO  🔍 Preload Zone Giorno: state=idle, available=true
[07:31:33.501] INFO  🔍 Preload Zone Giorno: SKIPPED - not available or powered
[07:31:33.516] INFO  Received message: (message_id, result, partial)
[07:31:33.516] INFO  🎛️ getPlayers returned 10 players:
[07:31:33.516] INFO  🎛️ After filtering: 10 players available
[07:31:33.516] INFO  🖼️ Preloading track info for all 10 players...
[07:31:33.516] INFO  🔍 Preload Camera dei BOSS: state=idle, available=true
[07:31:33.516] INFO  🔍 Preload Camera dei BOSS: SKIPPED - not available or powered
[07:31:33.516] INFO  🔍 Preload Camera Edo speaker: state=idle, available=true
[07:31:33.516] INFO  🔍 Preload Camera Edo speaker: SKIPPED - not

**Comment by Tyger375** [comment]
I do have music assistant auth, I created two users, mine has username "edoar" but there's no device in the list named like that

**Comment by CollotsSpot** [comment]
Thanks for the detailed logs! I can see exactly what's happening.

**The Issue:**
The app successfully gets the Sendspin connection info from your Music Assistant server, but the WebSocket connection to port 8927 times out:

```
Sendspin: Got connection info - local_ws_url: ws://192.168.1.100:8927/sendspin
Sendspin: Connection attempt failed: TimeoutException after 0:00:05.000000
```

**Quick Test:**
Can you check if local playback works in the Music Assistant web UI? If it doesn't work there either, then port 8927 (Sendspin) isn't accessible - which would explain why Ensemble can't connect.

**The Fix:**
If you're running Music Assistant in Docker, you need to expose port 8927.

**For Docker Compose**, add to your `docker-compose.yml`:
```yaml
ports:
  - "8095:8095"
  - "8927:8927"  # Add this line for Sendspin
```

**For Docker run**, add `-p 8927:8927` to your command.

After restarting the container with the port exposed, the app should be able to connect and register "edoar's Phone" as a local player.

Let me know how you get on!

**Comment by Tyger375** [comment]
thanks for the reply! when I set up music assistant server logs said music streaming was serving on port 8097 (I guess it's the default one).
do I have to change the port on the server or can I do it client side?

**Comment by CollotsSpot** [comment]
You need to add 8927 for sendspin, as well as 8097

**Comment by Tyger375** [comment]
woah can't believe I missed that! thank you, I'll try that when I get back home.
just out of curiosity, why does the webui work anyway? do they use different protocols for music streaming?

**Comment by swever826** [comment]
I am having the same issue. I get these messages in the log when I connect the app using a reverse proxy and also locally with an IP. In both scenarios I can't see my phone in the players options.

When using Music Assistant with the reverse proxy URL in my phone's browser, I don't have this issue and the device appears in the players list and I am able to listen to music from my phone. Also, the /sendspin endpoint seems to be accesible from my reverse proxy URL.

![File_20251219-152454.jpg](https://github.com/user-attachments/assets/50cd6cf2-df67-4711-ab01-a7b3f257d88f)

![File_20251219-152656.jpg](https://github.com/user-attachments/assets/fd99d83c-4041-40c4-a179-cf8a9f0b6a26)

**Comment by CollotsSpot** [comment]
Thanks for the logs and details! I've done some testing on my end and figured out what's needed.

**The issue:** When connecting via a reverse proxy, Ensemble needs to reach the Sendspin service on port 8927 - but most setups only expose the main MA port (8095).

**Good news:** You just need to add a few lines to your MA docker-compose.

### For Traefik (using labels)

Add these to your `docker-compose.yml`:

```yaml
services:
  musicassistant:
    ports:
      - "8095:8095"
      - "8927:8927"  # Add this for Sendspin
    labels:
      # ... your existing labels ...
      # Add these for Sendspin:
      - "traefik.http.routers.ma-sendspin.rule=Host(`your.domain.com`) && PathPrefix(`/sendspin`)"
      - "traefik.http.routers.ma-sendspin.entrypoints=websecure"
      - "traefik.http.routers.ma-sendspin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ma-sendspin.service=ma-sendspin"
      - "traefik.http.services.ma-sendspin.loadbalancer.server.port=8927"
```

### For Nginx

Add port 8927, then in your nginx config:
```nginx
location /sendspin {
    proxy_pass http://musicassistant:8927;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

After restarting, connect in Ensemble using your HTTPS URL (like `https://ma.yourdomain.com`) and your phone should show up as a player!

**Comment by CollotsSpot** [comment]
**Update: v2.3.0-beta released with simplified setup for MA 2.7.1+**

Great news! I've just released [v2.3.0-beta](https://github.com/CollotsSpot/Ensemble/releases/tag/v2.3.0-beta) which adds support for Music Assistant 2.7.1's new Sendspin proxy.

**If you're on MA 2.7.1 or later:**
- No need to expose port 8927
- No need for special `/sendspin` reverse proxy routes
- Just your standard HTTPS setup to port 8095 works out of the box

**If you're still on MA 2.7.0:**
- The Traefik/Nginx config from my previous comment still applies
- Consider updating to MA 2.7.1 for the simpler setup

@swever826 Can you try the new release and let me know if it works with your setup?

**Comment by swever826** [comment]
Thanks! But I am still getting the same errors in the log and I am not able to see my phone on the players list.

I am using Music Assistant 2.7.1 and your latest version of the app 2.3.0-beta

![File_20251219-174137.jpg](https://github.com/user-attachments/assets/59a6b52c-9529-4312-aca0-611841d00f84)

**Comment by CollotsSpot** [comment]
Thanks for the logs! That's strange - the error `Invalid command: sendspin/connection_info` suggests Sendspin isn't available on your server.

I've just tested this on my end with MA 2.7.1 beta - I removed port 8927 and deleted my `/sendspin` reverse proxy route entirely, and it works fine. So I'm a bit puzzled why it's not working for you.

A few things to check:

1. **Verify your MA version** - Go to Settings > About in the MA web UI and confirm it shows 2.7.1

2. **Enable Sendspin provider** - Go to Settings > Providers and make sure Sendspin is added and enabled

3. **Stable or beta?** - The Sendspin proxy feature is in the beta channel. If you're on stable, you may need to switch to beta or use the reverse proxy config from my earlier comment.

Also, can you copy and paste more of the logs from the app? Screenshots are hard to read - if you long-press in the debug log screen you can select and copy the text.

Let me know what you find!

**Comment by swever826** [comment]
The sendspin reverse proxy was added in the stable version 2.7.1 of Music Assistant. I am now on 2.7.2 and still having this issue.

I'm also using the latest version of your app. I tried removing cache and storage of the app, and tried connecting using an HTTP connection and local IP.

I don't know if its not working only for me or if I can try anything else?

Version of Music Assistant:
![File_20251221-103448.jpg](https://github.com/user-attachments/assets/adc35a46-f881-4773-88b1-ff44ab9546ad)

Sendspin Provider exists in my Music Assistant installation:
![File_20251221-104455.jpg](https://github.com/user-attachments/assets/2514e5df-bfb5-467f-b822-6a846d5f4f55)



Logs:
```
[10:27:11.310] INFO  Initializing database...
[10:27:11.311] INFO  Database initialized successfully
[10:27:11.311] INFO  💾 Database initialized
[10:27:11.355] INFO  Migration skipped - no ownerName to migrate
[10:27:11.355] INFO  📦 Loading library from database cache...
[10:27:11.357] INFO  📦 Loaded 0 albums, 0 artists, 0 audiobooks, 0 playlists from cache
[10:27:11.357] INFO  📦 Library cache loaded
[10:27:11.385] INFO  🎵 AudioService initialized - background playback and media notifications ENABLED
[10:27:23.815] INFO  🔍 Auto-detecting auth strategy for http://10.0.0.2:8095
[10:27:23.815] INFO  Normalized URL: http://10.0.0.2:8095
[10:27:23.816] INFO  Checking for Music Assistant native auth at http://10.0.0.2:8095...
[10:27:23.816] INFO  Checking MA API at: http://10.0.0.2:8095/api
[10:27:23.860] INFO  MA API response: 401
[10:27:23.860] INFO  MA API body: Authentication required
[10:27:23.860] INFO  MA API returned 401 - auth required
[10:27:23.860] INFO  ✓ Detected Music Assistant native authentication
[10:27:23.860] INFO  ✅ Auth detection successful with URL: http://10.0.0.2:8095
[10:27:26.674] INFO  📱 App resumed - checking WebSocket connection...
[10:27:26.674] INFO  🔄 checkAndReconnect called - state: MAConnectionState.disconnected
[10:27:26.674] INFO  🔄 No server URL saved, skipping reconnect
[10:27:29.071] INFO  📱 App resumed - checking WebSocket connection...
[10:27:29.071] INFO  🔄 checkAndReconnect called - state: MAConnectionState.disconnected
[10:27:29.071] INFO  🔄 No server URL saved, skipping reconnect
[10:27:30.240] INFO  Original server URL: http://10.0.0.2:8095
[10:27:30.241] INFO  Using WebSocket session ID: session_49b9632a-b76f-490a-9118-f58fb8299fd3
[10:27:30.241] INFO  Using custom WebSocket port from settings: 8095
[10:27:30.241] INFO  Attempting unsecure (WS) connection
[10:27:30.241] INFO  Final WebSocket URL: ws://10.0.0.2:8095/ws?client_id=session_49b9632a-b76f-490a-9118-f58fb8299fd3
[10:27:30.241] INFO  Connection: No authentication configured
[10:27:30.603] INFO  Received message: (server_id, server_version, schema_version, ..., homeassistant_addon, onboard_done)
[10:27:30.603] INFO  Received server info: 2.7.2 (schema: 28)
[10:27:30.603] INFO  Server: Requires authentication
[10:27:30.603] INFO  🔗 WebSocket connected to MA server
[10:27:30.603] INFO  🔐 MA auth required, attempting authentication...
[10:27:30.603] INFO  Connection: Connected to server
[10:27:30.603] INFO  🔐 Logging in with credentials...
[10:27:30.604] INFO  ❌ MA authentication failed - no valid token or credentials
[10:27:30.648] INFO  Received message: (message_id, result, partial)
[10:27:30.648] INFO  ✓ Got access token, authenticating session...
[10:27:30.682] INFO  Received message: (message_id, result, partial)
[10:27:30.682] INFO  ✅ Login and authentication successful
[10:27:30.682] INFO  Creating long-lived token...
[10:27:30.682] INFO  ✅ MA authentication successful
[10:27:30.682] INFO  🚀 Initializing after connection...
[10:27:30.682] INFO  📥 Fetching initial state...
[10:27:30.696] INFO  Received message: (message_id, error_code, details)
[10:27:30.696] INFO  Command error: 12 - Invalid command: auth/create_token
[10:27:30.696] INFO  ⚠️ Token creation error: Exception: 12: Invalid command: auth/create_token
[10:27:31.294] INFO  Received message: (message_id, result, partial)
[10:27:31.294] INFO  ✓ Provider manifests loaded
[10:27:31.306] INFO  🔄 Fetching fresh discover artists...
[10:27:31.307] INFO  🔄 Fetching fresh discover albums...
[10:27:31.315] INFO  Received message: (message_id, result, partial)
[10:27:31.315] INFO  ✓ Provider instances loaded
[10:27:31.315] INFO  ✅ Initial state fetch complete
[10:27:31.316] INFO  🔄 Fetching fresh recent albums from MA...
[10:27:31.342] INFO  Received message: (message_id, result, partial)
[10:27:31.344] INFO  Received message: (message_id, result, partial)
[10:27:31.345] INFO  Received message: (message_id, result, partial)
[10:27:31.345] INFO  Received message: (message_id, result, partial)
[10:27:31.345] INFO  Received message: (message_id, result, partial)
[10:27:31.345] INFO  ✅ Cached 9 discover artists
[10:27:31.345] INFO  ✅ Cached 10 discover albums
[10:27:31.345] INFO  🔍 auth/me raw response keys: [message_id, result, partial]
[10:27:31.345] INFO  ✓ Got user info: username=swever, display_name=Santiago
[10:27:31.354] INFO  ✅ Set owner name from MA profile: Santiago
[10:27:31.354] INFO  👻 Fresh install detected, searching for adoptable ghost for "Santiago"...
[10:27:31.354] INFO  Ghost adoption: Looking for existing player for "Santiago"
[10:27:31.358] INFO  Received message: (message_id, result, partial)
[10:27:31.358] INFO  Received message: (message_id, result, partial)
[10:27:31.358] INFO  Received message: (message_id, result, partial)
[10:27:31.360] INFO  Received message: (message_id, result, partial)
[10:27:31.361] INFO  Received message: (message_id, result, partial)
[10:27:31.361] INFO  Received message: (message_id, result, partial)
[10:27:31.361] INFO  Ghost adoption: Searching for "Santiago's Phone" or "Santiago's Phone"
[10:27:31.361] INFO  Ghost adoption: No existing player found
[10:27:31.365] INFO  Generated new player ID: ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[10:27:31.365] INFO  🆔 Using player ID: ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[10:27:31.366] INFO  📡 Server uses Sendspin (MA 2.7.0b20+), skipping builtin_player
[10:27:31.366] INFO  Sendspin: Auth token set for proxy authentication
[10:27:31.366] INFO  PcmAudioPlayer: Initializing (48000Hz, 2ch, 16bit)
[10:27:31.371] INFO  Received message: (message_id, result, partial)
[10:27:31.372] INFO  Received message: (message_id, result, partial)
[10:27:31.373] INFO  Received message: (message_id, result, partial)
[10:27:31.373] INFO  Received message: (message_id, result, partial)
[10:27:31.373] INFO  Received message: (message_id, result, partial)
[10:27:31.373] INFO  📚 Fetched 10 recent albums using 9 batch requests
[10:27:31.373] INFO  ✅ Cached 10 recent albums
[10:27:31.384] INFO  PcmAudioPlayer: Initialized successfully
[10:27:31.384] INFO  ✅ PCM audio player initialized for Sendspin
[10:27:31.384] INFO  PcmAudioPlayer: Connecting to audio stream
[10:27:31.384] INFO  Using existing player ID: ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[10:27:31.384] INFO  Sendspin: Getting connection info for player ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[10:27:31.388] INFO  Received message: (message_id, error_code, details)
[10:27:31.388] INFO  Command error: 12 - Invalid command: sendspin/connection_info
[10:27:31.388] INFO  Sendspin: Error getting connection info: Exception: 12: Invalid command: sendspin/connection_info
[10:27:31.388] INFO  ⚠️ Sendspin: WebRTC fallback not yet implemented
[10:27:31.388] INFO  ℹ️ For external access, configure /sendspin route in your reverse proxy
[10:27:31.388] INFO  ⚠️ Sendspin connection failed - local player unavailable
[10:27:31.399] INFO  Received message: (message_id, result, partial)
[10:27:31.399] INFO  🎛️ getPlayers returned 6 players:
[10:27:31.399] INFO  🎛️ After filtering: 6 players available
[10:27:31.399] INFO  🖼️ Preloading track info for all 6 players...
```

**Comment by CollotsSpot** [comment]
**Correction: `/sendspin` proxy requires MA 2.8.0+**

I apologize for the confusion in my earlier comments. After more research, I discovered that the `/sendspin` proxy endpoint was added in **Music Assistant 2.8.0** (beta channel), not 2.7.1.

**The situation:**
- **MA 2.7.x** (stable): No `/sendspin` proxy - you MUST expose port 8927 or configure your reverse proxy manually
- **MA 2.8.0+** (beta): Has built-in `/sendspin` proxy - works without exposing port 8927

@swever826 Your logs show you're on MA 2.7.2, which doesn't have the proxy. That's why you're seeing the connection failures.

**Options for MA 2.7.x users:**

1. **Upgrade to MA 2.8.0 beta** (recommended) - The proxy just works, no extra config needed

2. **Expose port 8927 in Docker** for local IP connections:
   ```yaml
   ports:
     - "8095:8095"
     - "8927:8927"
   ```

3. **Add reverse proxy route** for external access (if you prefer to stay on stable):
   - Traefik: Route `/sendspin` to service port 8927
   - Nginx: `location /sendspin { proxy_pass http://ma:8927; ... }`

**New build available:** I've released a build that:
- Detects your MA version and shows appropriate guidance in the logs
- Tries multiple connection strategies automatically
- Gives clear troubleshooting steps for your specific setup

Download: https://github.com/CollotsSpot/Ensemble/actions/runs/20416321868

Let me know how you get on! And again, apologies for the earlier misinformation.

**Comment by swever826** [comment]
Nope you were right the first time. The sendspin proxy was added in the stable release 2.7.1. You can see the [release notes](https://github.com/music-assistant/server/releases/tag/2.7.1).

Still, I changed to the latest beta and I have the same issue.

Music Assistant version:
![File_20251221-170220.jpg](https://github.com/user-attachments/assets/a316ad14-477b-46a6-91cf-622307b21232)

Accessing the Music Assistant from the browser correctly adds my phone as a sendspin player. Only using the Ensemble app fails to do that. Is there anything else I could try? I still don't know if it's only me with this issue.

Logs:
```
[16:56:43.415] INFO  Initializing database...
[16:56:43.415] INFO  Database initialized successfully
[16:56:43.415] INFO  💾 Database initialized
[16:56:43.430] INFO  Migration skipped - profiles already exist
[16:56:43.430] INFO  📦 Loading library from database cache...
[16:56:43.439] INFO  📦 Loaded 26 albums, 18 artists, 0 audiobooks, 60 playlists from cache
[16:56:43.439] INFO  📦 Library cache loaded
[16:56:43.474] INFO  🎵 AudioService initialized - background playback and media notifications ENABLED
[16:56:43.485] INFO  🚀 AppStartup: Waiting for provider auto-connection to http://10.0.0.2:8095
[16:56:43.485] INFO  🔐 Restoring saved auth credentials...
[16:56:43.485] INFO  ✓ Restored music_assistant credentials from storage
[16:56:43.485] INFO  🔐 Auth credentials restored: music_assistant
[16:56:43.486] INFO  Original server URL: http://10.0.0.2:8095
[16:56:43.486] INFO  Using WebSocket session ID: session_7b602cfa-481d-4ee4-9253-9b8ef9396045
[16:56:43.486] INFO  Using custom WebSocket port from settings: 8095
[16:56:43.486] INFO  Attempting unsecure (WS) connection
[16:56:43.486] INFO  Final WebSocket URL: ws://10.0.0.2:8095/ws?client_id=session_7b602cfa-481d-4ee4-9253-9b8ef9396045
[16:56:43.486] INFO  Connection: No authentication configured
[16:56:43.513] INFO  Received message: (server_id, server_version, schema_version, ..., homeassistant_addon, onboard_done)
[16:56:43.513] INFO  Received server info: 2.8.0b3 (schema: 28)
[16:56:43.513] INFO  Server: Requires authentication
[16:56:43.513] INFO  🔗 WebSocket connected to MA server
[16:56:43.514] INFO  🔐 MA auth required, attempting authentication...
[16:56:43.514] INFO  Connection: Connected to server
[16:56:43.514] INFO  🔐 Trying stored MA token...
[16:56:43.514] INFO  🔐 Authenticating WebSocket with token...
[16:56:43.520] INFO  Received message: (message_id, result, partial)
[16:56:43.520] INFO  ✅ WebSocket authenticated successfully
[16:56:43.520] INFO  ✅ MA authentication with stored token successful
[16:56:43.521] INFO  ✅ MA authentication successful
[16:56:43.521] INFO  🚀 Initializing after connection...
[16:56:43.521] INFO  📥 Fetching initial state...
[16:56:43.738] INFO  🚀 AppStartup: Connection established
[16:56:43.757] INFO  🔄 Fetching fresh discover artists...
[16:56:43.758] INFO  🔄 Fetching fresh discover albums...
[16:56:43.771] INFO  🔄 Fetching fresh recent albums from MA...
[16:56:43.979] INFO  Received message: (message_id, result, partial)
[16:56:43.979] INFO  Received message: (message_id, result, partial)
[16:56:43.979] INFO  ✓ Provider manifests loaded
[16:56:43.979] INFO  🔍 auth/me raw response keys: [message_id, result, partial]
[16:56:43.979] INFO  ✓ Got user info: username=swever, display_name=Santiago
[16:56:43.982] INFO  Received message: (message_id, result, partial)
[16:56:43.984] INFO  Received message: (message_id, result, partial)
[16:56:43.985] INFO  Received message: (message_id, result, partial)
[16:56:43.985] INFO  Received message: (message_id, result, partial)
[16:56:43.985] INFO  ✅ Cached 9 discover artists
[16:56:43.985] INFO  ✅ Cached 10 discover albums
[16:56:43.986] INFO  ✅ Set owner name from MA profile: Santiago
[16:56:43.993] INFO  Received message: (message_id, result, partial)
[16:56:43.993] INFO  ✓ Provider instances loaded
[16:56:43.993] INFO  ✅ Initial state fetch complete
[16:56:44.002] INFO  Received message: (message_id, result, partial)
[16:56:44.002] INFO  Received message: (message_id, result, partial)
[16:56:44.002] INFO  Received message: (message_id, result, partial)
[16:56:44.002] INFO  Received message: (message_id, result, partial)
[16:56:44.003] INFO  Received message: (message_id, result, partial)
[16:56:44.003] INFO  Received message: (message_id, result, partial)
[16:56:44.003] INFO  🔍 auth/me raw response keys: [message_id, result, partial]
[16:56:44.004] INFO  ✓ Got user info: username=swever, display_name=Santiago
[16:56:44.004] INFO  ✅ Set owner name from MA profile: Santiago
[16:56:44.004] INFO  Using existing player ID: ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[16:56:44.004] INFO  🆔 Using player ID: ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[16:56:44.005] INFO  📡 Server uses Sendspin (MA 2.7.0b20+), skipping builtin_player
[16:56:44.005] INFO  Sendspin: Auth token set for proxy authentication
[16:56:44.005] INFO  PcmAudioPlayer: Initializing (48000Hz, 2ch, 16bit)
[16:56:44.022] INFO  Received message: (message_id, result, partial)
[16:56:44.022] INFO  Received message: (message_id, result, partial)
[16:56:44.022] INFO  Received message: (message_id, result, partial)
[16:56:44.022] INFO  Received message: (message_id, result, partial)
[16:56:44.022] INFO  Received message: (message_id, result, partial)
[16:56:44.022] INFO  📚 Fetched 10 recent albums using 9 batch requests
[16:56:44.022] INFO  ✅ Cached 10 recent albums
[16:56:44.024] INFO  PcmAudioPlayer: Initialized successfully
[16:56:44.024] INFO  ✅ PCM audio player initialized for Sendspin
[16:56:44.024] INFO  PcmAudioPlayer: Connecting to audio stream
[16:56:44.024] INFO  Using existing player ID: ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[16:56:44.024] INFO  Sendspin: Getting connection info for player ensemble_2161ec67-d0c8-4b44-b4a0-552342bb3f82
[16:56:44.061] INFO  Received message: (message_id, error_code, details)
[16:56:44.062] INFO  Command error: 12 - Invalid command: sendspin/connection_info
[16:56:44.062] INFO  Sendspin: Error getting connection info: Exception: 12: Invalid command: sendspin/connection_info
[16:56:44.062] INFO  ⚠️ Sendspin: WebRTC fallback not yet implemented
[16:56:44.062] INFO  ℹ️ For external access, configure /sendspin route in your reverse proxy
[16:56:44.062] INFO  ⚠️ Sendspin connection failed - local player unavailable
[16:56:44.086] INFO  Received message: (message_id, result, partial)
[16:56:44.086] INFO  🎛️ getPlayers returned 6 players:
[16:56:44.086] INFO  🎛️ After filtering: 6 players available
```

**Comment by CollotsSpot** [comment]
Thanks for the detailed logs @swever826! 

**The issue is confirmed** - the logs show the app is calling `sendspin/connection_info` which doesn't exist in MA's API. This was a bug in my code where I incorrectly assumed that API existed.

Looking at your logs:
```
[16:56:44.024] INFO  Sendspin: Getting connection info for player...
[16:56:44.062] INFO  Command error: 12 - Invalid command: sendspin/connection_info
```

**The build I linked earlier contains the fix** - it removes that API call entirely and connects directly to port 8927 for local IPs like `10.0.0.2`. Can you confirm you installed the APK from the workflow artifacts?

Here's the direct link again: https://github.com/CollotsSpot/Ensemble/actions/runs/20424418382

Download the `ensemble-release-apk` artifact, unzip it, and install the APK. The new logs should show something like:
```
Sendspin: Local network detected, trying direct connection: ws://10.0.0.2:8927/sendspin
```

If you're not sure how to download from GitHub Actions, let me know and I can create a proper release.

**Comment by swever826** [comment]
Oops sorry I didn't see the last part of your message indicating the new build.

I installed it and it works for local connections using an IP! 🥳

I was using my tailscale URL to point directly to the 8095 port, so treating it as a local  was not working. When I point my Tailscale URL to the 10.0.0.2 server (no specific ports), it also works!!

Sadly using an HTTP URL doesn't work. I even mapped the /sendspin to 8927 port and it still showed the same errors on the log. I don't know if it is using wss:// instead of ws:// to connect to it?

Still now it works for my specific use case. Thanks!!

**Comment by CollotsSpot** [comment]
Very relived we got music playing for you 🤗
