### ISSUE TITLE
Favorites Button not working

### ISSUE THREAD

**Issue by shpongledsummer** [CollotsSpot/Ensemble#6]
This app is great already and works fast and smooth for me, thanks for creating it.

I noticed the button for liking a song is not actually adding it to the favorites. Instead it says "removed from favorites" each time it's pressed. 

Also I just noticed while trying to copy the relevant information from the log that I can only copy the whole error log and not individual text. Here it is:

[00:03:27.307] Event received: queue_time_updated
[00:03:27.309] Received message: (message_id, result, partial)
[00:03:27.677] Received message: (message_id, result, partial)
[00:03:28.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:28.306] Received message: (event, object_id, data)
[00:03:28.306] Event received: queue_time_updated
[00:03:28.307] Received message: (message_id, result, partial)
[00:03:29.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:29.296] Received message: (event, object_id, data)
[00:03:29.296] Event received: queue_time_updated
[00:03:29.296] Received message: (event, object_id, data)
[00:03:29.296] Event received: media_item_played
[00:03:29.301] Received message: (message_id, result, partial)
[00:03:29.301] Received message: (message_id, result, partial)
[00:03:29.314] Received message: (message_id, result, partial)
[00:03:29.561] Received message: (message_id, result, partial)
[00:03:30.276] Received message: (event, object_id, data)
[00:03:30.276] Event received: queue_time_updated
[00:03:30.288] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:30.294] Received message: (message_id, result, partial)
[00:03:31.276] Received message: (event, object_id, data)
[00:03:31.276] Event received: queue_time_updated
[00:03:31.282] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:31.292] Received message: (message_id, result, partial)
[00:03:31.303] Received message: (message_id, result, partial)
[00:03:32.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:32.308] Received message: (event, object_id, data)
[00:03:32.308] Event received: queue_time_updated
[00:03:32.309] Received message: (message_id, result, partial)
[00:03:33.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:33.313] Received message: (event, object_id, data)
[00:03:33.313] Event received: queue_time_updated
[00:03:33.314] Received message: (message_id, result, partial)
[00:03:34.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:34.305] Received message: (event, object_id, data)
[00:03:34.305] Event received: queue_time_updated
[00:03:34.314] Received message: (message_id, result, partial)
[00:03:34.314] Received message: (message_id, result, partial)
[00:03:34.324] Received message: (message_id, result, partial)
[00:03:34.424] Received message: (message_id, result, partial)
[00:03:34.743] Received message: (message_id, result, partial)
[00:03:34.745] Received message: (event, object_id, data)
[00:03:34.745] Event received: queue_updated
[00:03:34.745] Received message: (event, object_id, data)
[00:03:34.745] Event received: media_item_played
[00:03:34.746] Received message: (event, object_id, data)
[00:03:34.746] Event received: player_updated
[00:03:34.746] Event data: {"player_id":"media_player.gandalf_dlna","provider":"hass_players","type":"player","name":"Gandalf (DLNA)","available":true,"device_info":{"model":"WiiMu LinkPlayer","manufacturer":"wiimu","software_version":null,"model_id":null,"manufacturer_id":null,"ip_address":null,"mac_address":"00:22:6c:01:4b:ac"},"supported_features":["volume_mute","volume_set","pause"],"state":"paused","elapsed_time":0,"elapsed_time_last_updated":1764715648.7604742,"powered":true,"volume_level":0,"volume_muted":null,"group_childs":[],"can_group_with":[],"synced_to":null,"active_source":"media_player.gandalf_dlna","source_list":[],"active_group":null,"current_media":{"uri":"http://192.168.178.90:8097/flow/SzQioLHT/media_player.gandalf_dlna/c93c7f62d26541b994c74f21785e0777.mp3","media_type":"flow_stream","title":"Music Assistant","artist":null,"album":null,"image_url":"https://github.com/music-assistant/server/blob/dev/music_assistant/logo.png","duration":359,"queue_id":"media_player.gandalf_dlna","queue_item_id":"c93c7f62d26541b994c74f21785e0777","custom_data":null},"enabled_by_default":true,"hidden_by_default":false,"expose_to_ha_by_default":true,"needs_poll":false,"poll_interval":30,"enabled":true,"hide_player_in_ui":["when_group_active","when_unavailable","when_synced"],"expose_to_ha":true,"icon":"mdi-speaker","group_volume":0,"display_name":"Gandalf (DLNA)","extra_data":{"entity_registry_id":"7872cccc609691d5c5fa31f1e8863545","hass_domain":"dlna_dmr","hass_device_id":"3f4344560f097611018e75433752bf1d","hass_supported_features":479759},"announcement_in_progress":false,"power_control":"none","volume_control":"native","mute_control":"native"}
[00:03:34.759] Received message: (message_id, result, partial)
[00:03:34.768] Received message: (message_id, result, partial)
[00:03:34.784] Received message: (message_id, result, partial)
[00:03:34.886] Received message: (message_id, result, partial)
[00:03:35.284] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:35.332] Received message: (message_id, result, partial)
[00:03:36.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:36.309] Received message: (message_id, result, partial)
[00:03:37.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:37.310] Received message: (message_id, result, partial)
[00:03:38.281] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:38.300] Received message: (message_id, result, partial)
[00:03:39.284] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:39.292] Received message: (message_id, result, partial)
[00:03:39.791] Received message: (message_id, result, partial)
[00:03:39.803] Received message: (message_id, result, partial)
[00:03:39.894] Received message: (message_id, result, partial)
[00:03:40.284] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:40.311] Received message: (message_id, result, partial)
[00:03:41.281] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:41.287] Received message: (message_id, result, partial)
[00:03:42.282] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:42.305] Received message: (message_id, result, partial)
[00:03:43.281] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:43.289] Received message: (message_id, result, partial)
[00:03:44.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:44.291] Received message: (message_id, result, partial)
[00:03:44.788] Received message: (message_id, result, partial)
[00:03:44.798] Received message: (message_id, result, partial)
[00:03:44.909] Received message: (message_id, result, partial)
[00:03:45.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:45.310] Received message: (message_id, result, partial)
[00:03:46.284] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:46.311] Received message: (message_id, result, partial)
[00:03:47.304] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:47.343] Received message: (message_id, result, partial)
[00:03:48.284] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:48.293] Received message: (message_id, result, partial)
[00:03:49.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:49.292] Received message: (message_id, result, partial)
[00:03:49.790] Received message: (message_id, result, partial)
[00:03:49.802] Received message: (message_id, result, partial)
[00:03:49.903] Received message: (message_id, result, partial)
[00:03:50.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:50.308] Received message: (message_id, result, partial)
[00:03:51.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:51.316] Received message: (message_id, result, partial)
[00:03:52.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:52.292] Received message: (message_id, result, partial)
[00:03:53.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:53.291] Received message: (message_id, result, partial)
[00:03:54.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:54.314] Received message: (message_id, result, partial)
[00:03:54.790] Received message: (message_id, result, partial)
[00:03:54.801] Received message: (message_id, result, partial)
[00:03:54.940] Received message: (message_id, result, partial)
[00:03:55.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:55.310] Received message: (message_id, result, partial)
[00:03:56.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:56.291] Received message: (message_id, result, partial)
[00:03:57.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:57.308] Received message: (message_id, result, partial)
[00:03:58.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:58.291] Received message: (message_id, result, partial)
[00:03:59.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:03:59.308] Received message: (message_id, result, partial)
[00:03:59.790] Received message: (message_id, result, partial)
[00:03:59.800] Received message: (message_id, result, partial)
[00:03:59.905] Received message: (message_id, result, partial)
[00:04:00.282] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:00.300] Received message: (message_id, result, partial)
[00:04:01.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:01.291] Received message: (message_id, result, partial)
[00:04:02.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:02.310] Received message: (message_id, result, partial)
[00:04:03.281] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:03.308] Received message: (message_id, result, partial)
[00:04:04.284] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:04.303] Received message: (message_id, result, partial)
[00:04:04.787] Received message: (message_id, result, partial)
[00:04:04.800] Received message: (message_id, result, partial)
[00:04:04.898] Received message: (message_id, result, partial)
[00:04:04.900] Received message: (event, object_id, data)
[00:04:04.900] Event received: queue_updated
[00:04:04.900] Received message: (event, object_id, data)
[00:04:04.900] Event received: media_item_played
[00:04:04.900] Received message: (event, object_id, data)
[00:04:04.900] Event received: player_updated
[00:04:04.900] Event data: {"player_id":"media_player.gandalf_dlna","provider":"hass_players","type":"player","name":"Gandalf (DLNA)","available":true,"device_info":{"model":"WiiMu LinkPlayer","manufacturer":"wiimu","software_version":null,"model_id":null,"manufacturer_id":null,"ip_address":null,"mac_address":"00:22:6c:01:4b:ac"},"supported_features":["volume_mute","volume_set","pause"],"state":"idle","elapsed_time":0,"elapsed_time_last_updated":1764715648.7604742,"powered":true,"volume_level":0,"volume_muted":null,"group_childs":[],"can_group_with":[],"synced_to":null,"active_source":"media_player.gandalf_dlna","source_list":[],"active_group":null,"current_media":{"uri":"http://192.168.178.90:8097/flow/SzQioLHT/media_player.gandalf_dlna/c93c7f62d26541b994c74f21785e0777.mp3","media_type":"flow_stream","title":"Music Assistant","artist":null,"album":null,"image_url":"https://github.com/music-assistant/server/blob/dev/music_assistant/logo.png","duration":359,"queue_id":"media_player.gandalf_dlna","queue_item_id":"c93c7f62d26541b994c74f21785e0777","custom_data":null},"enabled_by_default":true,"hidden_by_default":false,"expose_to_ha_by_default":true,"needs_poll":false,"poll_interval":30,"enabled":true,"hide_player_in_ui":["when_group_active","when_unavailable","when_synced"],"expose_to_ha":true,"icon":"mdi-speaker","group_volume":0,"display_name":"Gandalf (DLNA)","extra_data":{"entity_registry_id":"7872cccc609691d5c5fa31f1e8863545","hass_domain":"dlna_dmr","hass_device_id":"3f4344560f097611018e75433752bf1d","hass_supported_features":479759},"announcement_in_progress":false,"power_control":"none","volume_control":"native","mute_control":"native"}
[00:04:05.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:05.310] Received message: (message_id, result, partial)
[00:04:06.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:06.292] Received message: (message_id, result, partial)
[00:04:07.284] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:07.308] Received message: (message_id, result, partial)
[00:04:08.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:08.308] Received message: (message_id, result, partial)
[00:04:09.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:09.291] Received message: (message_id, result, partial)
[00:04:09.789] Received message: (message_id, result, partial)
[00:04:10.281] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:10.291] Received message: (message_id, result, partial)
[00:04:11.302] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:11.310] Received message: (message_id, result, partial)
[00:04:12.283] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:12.292] Received message: (message_id, result, partial)
[00:04:18.126] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:18.154] Received message: (message_id, result, partial)
[00:04:19.126] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:19.153] Received message: (message_id, result, partial)
[00:04:19.632] Received message: (message_id, result, partial)
[00:04:20.127] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:20.158] Received message: (message_id, result, partial)
[00:04:20.991] WebSocket connection closed
[00:04:21.127] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:21.128] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:31.161] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:31.161] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:32.160] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:32.161] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:33.160] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:33.160] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:34.160] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:34.161] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:35.160] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:35.160] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:36.160] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:36.161] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:37.161] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:37.161] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:04:44.508] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:04:44.508] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:17.480] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:17.480] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:19.751] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:19.752] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:44.479] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:44.479] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:45.438] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:45.439] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:46.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:46.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:47.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:47.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:48.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:48.438] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:49.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:49.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:50.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:50.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:51.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:51.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:52.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:52.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:53.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:53.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:54.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:54.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:55.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:55.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:56.438] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:56.438] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:05:57.437] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:05:57.437] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:06:00.839] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:06:00.839] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:06:01.838] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:06:01.839] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:06:02.838] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:06:02.839] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:06:25.904] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:06:25.905] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:06:29.589] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:06:29.590] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:07:00.368] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:07:00.368] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:07:03.550] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:07:03.550] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:07:35.422] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:07:35.422] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:07:38.848] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:07:38.849] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:08:12.479] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:08:12.479] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:08:44.346] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:08:44.346] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:08:56.219] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:08:56.219] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:08:57.220] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:08:57.220] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:08:58.219] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:08:58.220] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:08:59.221] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:08:59.221] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:09:00.220] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:00.220] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:09:01.220] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:01.220] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:09:02.221] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:02.222] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:09:03.220] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:03.220] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:09:04.220] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:04.220] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:09:05.195] Original server URL: http://192.168.178.90:8095
[00:09:05.195] Using existing client ID: cb4e7114-113d-44cd-beb9-1fe1d251378e
[00:09:05.196] Using custom WebSocket port from settings: 8095
[00:09:05.196] Attempting unsecure (WS) connection
[00:09:05.196] Final WebSocket URL: ws://192.168.178.90:8095/ws?client_id=cb4e7114-113d-44cd-beb9-1fe1d251378e
[00:09:05.196] ℹ️ No authentication configured for WebSocket
[00:09:05.219] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:05.219] ❌ Error updating built-in player state: Exception: Not connected to Music Assistant server
[00:09:05.228] Received message: (server_id, server_version, schema_version, ..., homeassistant_addon, onboard_done)
[00:09:05.228] Received server info: 2.6.2
[00:09:05.229] Connected to Music Assistant successfully
[00:09:05.229] 🎵 Registering builtin player: id=cb4e7114-113d-44cd-beb9-1fe1d251378e, name=Ben
[00:09:05.243] Received message: (message_id, result, partial)
[00:09:05.243] Received message: (message_id, result, partial)
[00:09:05.243] Received message: (event, object_id, data)
[00:09:05.243] Event received: player_updated
[00:09:05.243] Event data: {"player_id":"cb4e7114-113d-44cd-beb9-1fe1d251378e","provider":"builtin_player","type":"player","name":"Ben","available":true,"device_info":{"model":"Unknown model","manufacturer":"Unknown Manufacturer","software_version":null,"model_id":null,"manufacturer_id":null,"ip_address":null,"mac_address":null},"supported_features":["volume_mute","power","volume_set","pause"],"state":"idle","elapsed_time":null,"elapsed_time_last_updated":null,"powered":false,"volume_level":null,"volume_muted":null,"group_childs":[],"can_group_with":[],"synced_to":null,"active_source":"cb4e7114-113d-44cd-beb9-1fe1d251378e","source_list":[],"active_group":null,"current_media":null,"enabled_by_default":true,"hidden_by_default":true,"expose_to_ha_by_default":false,"needs_poll":true,"poll_interval":30,"enabled":true,"hide_player_in_ui":["always"],"expose_to_ha":false,"icon":"mdi-speaker","group_volume":0,"display_name":"Ben","extra_data":{},"announcement_in_progress":false,"power_control":"native","volume_control":"native","mute_control":"native"}
[00:09:05.243] ✅ Builtin player registered successfully
[00:09:05.279] Received message: (message_id, result, partial)
[00:09:05.312] Received message: (message_id, result, partial)
[00:09:05.411] Received message: (message_id, result, partial)
[00:09:05.411] Received message: (message_id, result, partial)
[00:09:05.417] Received message: (message_id, result, partial)
[00:09:05.417] ⚠️ Queue is empty or all items failed to parse
[00:09:06.244] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:06.574] Received message: (message_id, result, partial)
[00:09:06.574] Received message: (message_id, result, partial)
[00:09:06.584] Received message: (message_id, result, partial)
[00:09:06.584] Received message: (message_id, result, partial)
[00:09:06.584] Received message: (message_id, result, partial)
[00:09:06.596] Received message: (message_id, result, partial)
[00:09:06.609] Received message: (message_id, result, partial)
[00:09:06.623] Received message: (message_id, result, partial)
[00:09:06.636] Received message: (message_id, result, partial)
[00:09:06.649] Received message: (message_id, result, partial)
[00:09:06.662] Received message: (message_id, result, partial)
[00:09:06.677] Received message: (message_id, result, partial)
[00:09:06.692] Received message: (message_id, result, partial)
[00:09:06.710] Received message: (message_id, result, partial)
[00:09:06.723] Received message: (message_id, result, partial)
[00:09:07.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:07.270] Received message: (message_id, result, partial)
[00:09:08.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:08.251] Received message: (message_id, result, partial)
[00:09:09.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:09.279] Received message: (message_id, result, partial)
[00:09:10.252] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:10.275] Received message: (message_id, result, partial)
[00:09:10.275] Received message: (message_id, result, partial)
[00:09:10.296] Received message: (message_id, result, partial)
[00:09:10.318] Received message: (message_id, result, partial)
[00:09:10.318] ⚠️ Queue is empty or all items failed to parse
[00:09:11.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:11.255] Received message: (message_id, result, partial)
[00:09:12.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:12.277] Received message: (message_id, result, partial)
[00:09:13.047] Received message: (message_id, result, partial)
[00:09:13.134] Received message: (message_id, result, partial)
[00:09:13.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:13.262] Received message: (message_id, result, partial)
[00:09:14.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:14.272] Received message: (message_id, result, partial)
[00:09:15.248] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:15.278] Received message: (message_id, result, partial)
[00:09:15.278] Received message: (message_id, result, partial)
[00:09:15.288] Received message: (message_id, result, partial)
[00:09:15.295] Received message: (message_id, result, partial)
[00:09:15.295] ⚠️ Queue is empty or all items failed to parse
[00:09:15.339] Received message: (event, object_id, data)
[00:09:15.339] Event received: player_updated
[00:09:15.340] Event data: {"player_id":"media_player.gandalf_dlna","provider":"hass_players","type":"player","name":"Gandalf (DLNA)","available":true,"device_info":{"model":"WiiMu LinkPlayer","manufacturer":"wiimu","software_version":null,"model_id":null,"manufacturer_id":null,"ip_address":null,"mac_address":"00:22:6c:01:4b:ac"},"supported_features":["volume_mute","volume_set","pause"],"state":"idle","elapsed_time":0,"elapsed_time_last_updated":1764715648.7604742,"powered":true,"volume_level":18,"volume_muted":null,"group_childs":[],"can_group_with":[],"synced_to":null,"active_source":"media_player.gandalf_dlna","source_list":[],"active_group":null,"current_media":{"uri":"","media_type":"flow_stream","title":"Music Assistant","artist":null,"album":null,"image_url":"https://github.com/music-assistant/server/blob/dev/music_assistant/logo.png","duration":359,"queue_id":"media_player.gandalf_dlna","queue_item_id":"c93c7f62d26541b994c74f21785e0777","custom_data":null},"enabled_by_default":true,"hidden_by_default":false,"expose_to_ha_by_default":true,"needs_poll":false,"poll_interval":30,"enabled":true,"hide_player_in_ui":["when_group_active","when_unavailable","when_synced"],"expose_to_ha":true,"icon":"mdi-speaker","group_volume":18,"display_name":"Gandalf (DLNA)","extra_data":{"entity_registry_id":"7872cccc609691d5c5fa31f1e8863545","hass_domain":"dlna_dmr","hass_device_id":"3f4344560f097611018e75433752bf1d","hass_supported_features":479759},"announcement_in_progress":false,"power_control":"none","volume_control":"native","mute_control":"native"}
[00:09:15.560] Received message: (message_id, result, partial)
[00:09:16.204] Received message: (event, object_id, data)
[00:09:16.204] Event received: queue_updated
[00:09:16.205] Received message: (event, object_id, data)
[00:09:16.205] Event received: media_item_played
[00:09:16.206] Received message: (event, object_id, data)
[00:09:16.206] Event received: player_updated
[00:09:16.206] Event data: {"player_id":"media_player.gandalf_dlna","provider":"hass_players","type":"player","name":"Gandalf (DLNA)","available":true,"device_info":{"model":"WiiMu LinkPlayer","manufacturer":"wiimu","software_version":null,"model_id":null,"manufacturer_id":null,"ip_address":null,"mac_address":"00:22:6c:01:4b:ac"},"supported_features":["volume_mute","volume_set","pause"],"state":"playing","elapsed_time":0,"elapsed_time_last_updated":1764715648.7604742,"powered":true,"volume_level":18,"volume_muted":null,"group_childs":[],"can_group_with":[],"synced_to":null,"active_source":"media_player.gandalf_dlna","source_list":[],"active_group":null,"current_media":{"uri":"","media_type":"flow_stream","title":"Music Assistant","artist":null,"album":null,"image_url":"https://github.com/music-assistant/server/blob/dev/music_assistant/logo.png","duration":359,"queue_id":"media_player.gandalf_dlna","queue_item_id":"c93c7f62d26541b994c74f21785e0777","custom_data":null},"enabled_by_default":true,"hidden_by_default":false,"expose_to_ha_by_default":true,"needs_poll":false,"poll_interval":30,"enabled":true,"hide_player_in_ui":["when_group_active","when_unavailable","when_synced"],"expose_to_ha":true,"icon":"mdi-speaker","group_volume":18,"display_name":"Gandalf (DLNA)","extra_data":{"entity_registry_id":"7872cccc609691d5c5fa31f1e8863545","hass_domain":"dlna_dmr","hass_device_id":"3f4344560f097611018e75433752bf1d","hass_supported_features":479759},"announcement_in_progress":false,"power_control":"none","volume_control":"native","mute_control":"native"}
[00:09:16.207] Received message: (event, object_id, data)
[00:09:16.207] Event received: queue_time_updated
[00:09:16.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:16.252] Received message: (message_id, result, partial)
[00:09:17.186] Received message: (event, object_id, data)
[00:09:17.186] Event received: queue_time_updated
[00:09:17.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:17.254] Received message: (message_id, result, partial)
[00:09:18.189] Received message: (event, object_id, data)
[00:09:18.189] Event received: queue_time_updated
[00:09:18.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:18.257] Received message: (message_id, result, partial)
[00:09:19.187] Received message: (event, object_id, data)
[00:09:19.188] Event received: queue_time_updated
[00:09:19.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:19.254] Received message: (message_id, result, partial)
[00:09:19.536] Received message: (event, object_id, data)
[00:09:19.536] Event received: queue_time_updated
[00:09:20.215] Received message: (event, object_id, data)
[00:09:20.215] Event received: queue_time_updated
[00:09:20.220] Received message: (message_id, error_code, details)
[00:09:20.220] Command error: 12 - Invalid command: music/favorites/toggle
[00:09:20.220] Error toggling favorite: Exception: 12: Invalid command: music/favorites/toggle
[00:09:20.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:20.256] Received message: (message_id, result, partial)
[00:09:20.256] Received message: (message_id, result, partial)
[00:09:20.264] Received message: (message_id, result, partial)
[00:09:20.273] Received message: (message_id, result, partial)
[00:09:20.274] ⚠️ Queue is empty or all items failed to parse
[00:09:21.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:21.270] Received message: (event, object_id, data)
[00:09:21.270] Event received: queue_time_updated
[00:09:21.272] Received message: (message_id, result, partial)
[00:09:22.242] Received message: (event, object_id, data)
[00:09:22.243] Event received: queue_time_updated
[00:09:22.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:22.251] Received message: (message_id, result, partial)
[00:09:22.676] Received message: (message_id, error_code, details)
[00:09:22.676] Command error: 12 - Invalid command: music/favorites/toggle
[00:09:22.677] Error toggling favorite: Exception: 12: Invalid command: music/favorites/toggle
[00:09:23.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:23.266] Received message: (event, object_id, data)
[00:09:23.267] Event received: queue_time_updated
[00:09:23.268] Received message: (message_id, result, partial)
[00:09:24.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:24.271] Received message: (event, object_id, data)
[00:09:24.272] Event received: queue_time_updated
[00:09:24.272] Received message: (message_id, result, partial)
[00:09:25.197] Received message: (event, object_id, data)
[00:09:25.197] Event received: queue_time_updated
[00:09:25.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:25.255] Received message: (message_id, result, partial)
[00:09:25.256] Received message: (message_id, result, partial)
[00:09:25.264] Received message: (message_id, result, partial)
[00:09:25.271] Received message: (message_id, result, partial)
[00:09:25.272] ⚠️ Queue is empty or all items failed to parse
[00:09:26.235] Received message: (event, object_id, data)
[00:09:26.236] Event received: queue_time_updated
[00:09:26.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:26.253] Received message: (message_id, result, partial)
[00:09:27.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:27.269] Received message: (event, object_id, data)
[00:09:27.269] Event received: queue_time_updated
[00:09:27.269] Received message: (message_id, result, partial)
[00:09:27.639] Received message: (message_id, error_code, details)
[00:09:27.639] Command error: 12 - Invalid command: music/favorites/toggle
[00:09:27.639] Error toggling favorite: Exception: 12: Invalid command: music/favorites/toggle
[00:09:28.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:28.271] Received message: (event, object_id, data)
[00:09:28.272] Event received: queue_time_updated
[00:09:28.272] Received message: (message_id, result, partial)
[00:09:29.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:29.270] Received message: (event, object_id, data)
[00:09:29.270] Event received: queue_time_updated
[00:09:29.270] Received message: (event, object_id, data)
[00:09:29.271] Event received: media_item_played
[00:09:29.272] Received message: (message_id, result, partial)
[00:09:30.230] Received message: (event, object_id, data)
[00:09:30.230] Event received: queue_time_updated
[00:09:30.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:30.292] Received message: (message_id, result, partial)
[00:09:30.292] Received message: (message_id, result, partial)
[00:09:30.298] Received message: (message_id, result, partial)
[00:09:30.304] Received message: (message_id, result, partial)
[00:09:30.304] ⚠️ Queue is empty or all items failed to parse
[00:09:31.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:31.254] Received message: (event, object_id, data)
[00:09:31.254] Event received: queue_time_updated
[00:09:31.265] Received message: (message_id, result, partial)
[00:09:32.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:32.281] Received message: (event, object_id, data)
[00:09:32.281] Event received: queue_time_updated
[00:09:32.281] Received message: (message_id, result, partial)
[00:09:33.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:33.283] Received message: (event, object_id, data)
[00:09:33.284] Event received: queue_time_updated
[00:09:33.287] Received message: (message_id, result, partial)
[00:09:34.221] Received message: (event, object_id, data)
[00:09:34.221] Event received: queue_time_updated
[00:09:34.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:34.255] Received message: (message_id, result, partial)
[00:09:35.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:35.249] Received message: (event, object_id, data)
[00:09:35.250] Event received: queue_time_updated
[00:09:35.258] Received message: (message_id, result, partial)
[00:09:35.259] Received message: (message_id, result, partial)
[00:09:35.265] Received message: (message_id, result, partial)
[00:09:35.273] Received message: (message_id, result, partial)
[00:09:35.273] ⚠️ Queue is empty or all items failed to parse
[00:09:36.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:36.271] Received message: (event, object_id, data)
[00:09:36.271] Event received: queue_time_updated
[00:09:36.274] Received message: (message_id, result, partial)
[00:09:37.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:37.269] Received message: (event, object_id, data)
[00:09:37.270] Event received: queue_time_updated
[00:09:37.271] Received message: (message_id, result, partial)
[00:09:38.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:38.281] Received message: (event, object_id, data)
[00:09:38.281] Event received: queue_time_updated
[00:09:38.283] Received message: (message_id, result, partial)
[00:09:39.241] Received message: (event, object_id, data)
[00:09:39.241] Event received: queue_time_updated
[00:09:39.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:39.256] Received message: (message_id, result, partial)
[00:09:40.249] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:40.288] Received message: (event, object_id, data)
[00:09:40.288] Event received: queue_time_updated
[00:09:40.294] Received message: (message_id, result, partial)
[00:09:40.294] Received message: (message_id, result, partial)
[00:09:40.302] Received message: (message_id, result, partial)
[00:09:40.309] Received message: (message_id, result, partial)
[00:09:40.309] ⚠️ Queue is empty or all items failed to parse
[00:09:41.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:41.285] Received message: (event, object_id, data)
[00:09:41.286] Event received: queue_time_updated
[00:09:41.292] Received message: (message_id, result, partial)
[00:09:42.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:42.267] Received message: (event, object_id, data)
[00:09:42.267] Event received: queue_time_updated
[00:09:42.269] Received message: (message_id, result, partial)
[00:09:43.234] Received message: (event, object_id, data)
[00:09:43.234] Event received: queue_time_updated
[00:09:43.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:43.254] Received message: (message_id, result, partial)
[00:09:44.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:44.257] Received message: (event, object_id, data)
[00:09:44.257] Event received: queue_time_updated
[00:09:44.259] Received message: (message_id, result, partial)
[00:09:45.247] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:45.279] Received message: (event, object_id, data)
[00:09:45.279] Event received: queue_time_updated
[00:09:45.284] Received message: (message_id, result, partial)
[00:09:45.285] Received message: (message_id, result, partial)
[00:09:45.291] Received message: (message_id, result, partial)
[00:09:45.297] Received message: (message_id, result, partial)
[00:09:45.297] ⚠️ Queue is empty or all items failed to parse
[00:09:46.246] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:46.282] Received message: (event, object_id, data)
[00:09:46.283] Event received: queue_time_updated
[00:09:46.283] Received message: (message_id, result, partial)
[00:09:47.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:47.268] Received message: (event, object_id, data)
[00:09:47.268] Event received: queue_time_updated
[00:09:47.272] Received message: (message_id, result, partial)
[00:09:48.245] 📊 Updating builtin player state: powered=true, playing=false, paused=false, position=0, volume=100, muted=false
[00:09:48.253] Received message: (event, object_id, data)
[00:09:48.253] Event received: queue_time_updated
[00:09:48.271] Received message: (message_id, result, partial)

**Comment by CollotsSpot** [comment]
Thank a lot for the feedback! May I ask your setup? How are you logging in? Any Auth?

**Comment by ghost** [comment]
My setup is just Music Assistant installed as an Add-On on my local Home Assistant Server.

I Just entered my servers URL and it instantly logged me in, i did not need to enter any login detail. My speaker setup consists of 6 Linkplay devices which are configured via the DLNA integration as Music Assitant does not support my speakers natively.

**Comment by CollotsSpot** [comment]
@shpongledsummer favourites bottom should be fixed in new release

**Comment by ghost** [comment]
I just tested it with the newest version. Unfortunately, the favorites button still doesn’t seem to work for me. The heart icon fills in, but as soon as I navigate away and come back, it appears greyed out again. I checked the log but couldn’t find any relevant information about this

**Comment by CollotsSpot** [comment]
Hmm, I thought that was fixed. Same behaviour here. I'm on it

**Comment by CollotsSpot** [comment]
Just put out a new release. Should be fixed now

**Comment by ghost** [comment]
Favorites button is working now, I just tested with albums and artists. Thank you! :)

Just a note: I couldn’t find a way to add a single track to favorites. It would be super nice if the favorites button could also be added to other sections like the now playing screen.

**Comment by CollotsSpot** [comment]
@shpongledsummer Added in new release
